// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: strawhouse-proto/_driver/feed.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
}

func (x *UploadFeedRequest) Reset() {
	*x = UploadFeedRequest{}
	mi := &file_strawhouse_proto__driver_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFeedRequest) ProtoMessage() {}

func (x *UploadFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strawhouse_proto__driver_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFeedRequest.ProtoReflect.Descriptor instead.
func (*UploadFeedRequest) Descriptor() ([]byte, []int) {
	return file_strawhouse_proto__driver_feed_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFeedRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type UploadFeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directory string `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"`
	Hash      string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Attr      []byte `protobuf:"bytes,4,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *UploadFeedResponse) Reset() {
	*x = UploadFeedResponse{}
	mi := &file_strawhouse_proto__driver_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFeedResponse) ProtoMessage() {}

func (x *UploadFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strawhouse_proto__driver_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFeedResponse.ProtoReflect.Descriptor instead.
func (*UploadFeedResponse) Descriptor() ([]byte, []int) {
	return file_strawhouse_proto__driver_feed_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFeedResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFeedResponse) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *UploadFeedResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UploadFeedResponse) GetAttr() []byte {
	if x != nil {
		return x.Attr
	}
	return nil
}

var File_strawhouse_proto__driver_feed_proto protoreflect.FileDescriptor

var file_strawhouse_proto__driver_feed_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x74, 0x72, 0x61, 0x77, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x5f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x11,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x22,
	0x6e, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x74, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x32,
	0x4d, 0x0a, 0x0a, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x64, 0x12, 0x3f, 0x0a,
	0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strawhouse_proto__driver_feed_proto_rawDescOnce sync.Once
	file_strawhouse_proto__driver_feed_proto_rawDescData = file_strawhouse_proto__driver_feed_proto_rawDesc
)

func file_strawhouse_proto__driver_feed_proto_rawDescGZIP() []byte {
	file_strawhouse_proto__driver_feed_proto_rawDescOnce.Do(func() {
		file_strawhouse_proto__driver_feed_proto_rawDescData = protoimpl.X.CompressGZIP(file_strawhouse_proto__driver_feed_proto_rawDescData)
	})
	return file_strawhouse_proto__driver_feed_proto_rawDescData
}

var file_strawhouse_proto__driver_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_strawhouse_proto__driver_feed_proto_goTypes = []any{
	(*UploadFeedRequest)(nil),  // 0: proto.UploadFeedRequest
	(*UploadFeedResponse)(nil), // 1: proto.UploadFeedResponse
}
var file_strawhouse_proto__driver_feed_proto_depIdxs = []int32{
	0, // 0: proto.DriverFeed.Upload:input_type -> proto.UploadFeedRequest
	1, // 1: proto.DriverFeed.Upload:output_type -> proto.UploadFeedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_strawhouse_proto__driver_feed_proto_init() }
func file_strawhouse_proto__driver_feed_proto_init() {
	if File_strawhouse_proto__driver_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strawhouse_proto__driver_feed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strawhouse_proto__driver_feed_proto_goTypes,
		DependencyIndexes: file_strawhouse_proto__driver_feed_proto_depIdxs,
		MessageInfos:      file_strawhouse_proto__driver_feed_proto_msgTypes,
	}.Build()
	File_strawhouse_proto__driver_feed_proto = out.File
	file_strawhouse_proto__driver_feed_proto_rawDesc = nil
	file_strawhouse_proto__driver_feed_proto_goTypes = nil
	file_strawhouse_proto__driver_feed_proto_depIdxs = nil
}
